-- =====================================================
-- SEED MORE PRODUCTS - Sản phẩm thật cho các category 25-33
-- =====================================================

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- Thêm một số brand nếu chưa có
INSERT INTO brand (name, slug, image, active) VALUES
('Asus', 'asus', NULL, 1)
ON DUPLICATE KEY UPDATE name=VALUES(name);

-- Lấy brand IDs
SET @sony = (SELECT id FROM brand WHERE slug='sony');
SET @microsoft = (SELECT id FROM brand WHERE slug='microsoft');
SET @bitdo = (SELECT id FROM brand WHERE slug='8bitdo');
SET @razer = (SELECT id FROM brand WHERE slug='razer');
SET @corsair = (SELECT id FROM brand WHERE slug='corsair');
SET @logitech = (SELECT id FROM brand WHERE slug='logitech');
SET @sandisk = (SELECT id FROM brand WHERE slug='sandisk');
SET @kingston = (SELECT id FROM brand WHERE slug='kingston');
SET @wd = (SELECT id FROM brand WHERE slug='western-digital');
SET @samsung = (SELECT id FROM brand WHERE slug='samsung');
SET @tplink = (SELECT id FROM brand WHERE slug='tp-link');
SET @asus = (SELECT id FROM brand WHERE slug='asus');
SET @ugreen = (SELECT id FROM brand WHERE slug='ugreen');
SET @baseus = (SELECT id FROM brand WHERE slug='baseus');
SET @xiaomi = (SELECT id FROM brand WHERE slug='xiaomi');

-- 25. TAY CẦM CHƠI GAME
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('Tay cầm Sony DualSense Wireless Controller', 'sony-dualsense-wireless-controller', 'TC-SONY-DS5', @sony, 1990000, 1790000, 'https://m.media-amazon.com/images/I/612bjwBuobS._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, '1560mAh', '280g', 50, 1, 1, NOW(), 'Tay cầm PS5 Sony DualSense với Haptic Feedback và Adaptive Triggers.', '<h2>Sony DualSense</h2><p>Trải nghiệm chơi game chân thực với Haptic Feedback và Adaptive Triggers trên tay cầm DualSense. Tương thích PS5 và PC.</p>', 'Tặng bọc cần gạt', '{"Kết nối":"Bluetooth/USB-C","Pin":"1560mAh","Tương thích":"PS5, PC, Mac, iOS, Android","Tính năng":"Haptic Feedback, Adaptive Triggers"}', 'Tay cầm Sony DualSense', 'Mua tay cầm Sony DualSense chính hãng giá tốt.', 25),
('Tay cầm Xbox Wireless Controller', 'xbox-wireless-controller', 'TC-MS-XBOX', @microsoft, 1690000, 1490000, 'https://m.media-amazon.com/images/I/51rP0iYfFjL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, 'Pin AA', '275g', 40, 1, 1, NOW(), 'Tay cầm Xbox Wireless thế hệ mới tương thích PC, Xbox Series X/S.', '<h2>Xbox Wireless Controller</h2><p>Thiết kế công thái học hiện đại, D-pad mới và nút Share chuyên dụng. Hỗ trợ kết nối Xbox Wireless và Bluetooth.</p>', 'Tặng pin AA Energizer', '{"Kết nối":"Xbox Wireless, Bluetooth, USB-C","Pin":"2x AA","Tương thích":"Xbox Series X/S, PC, Android, iOS","Tính năng":"Nút Share, D-pad Hybrid"}', 'Tay cầm Xbox Wireless Controller', 'Mua tay cầm Xbox Wireless chính hãng Microsoft.', 25),
('Tay cầm 8BitDo Ultimate Bluetooth', '8bitdo-ultimate-bluetooth', 'TC-8B-ULT', @bitdo, 1490000, 1290000, 'https://m.media-amazon.com/images/I/61j63m8iR3L._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, '1000mAh', '228g', 30, 0, 1, NOW(), 'Tay cầm 8BitDo Ultimate với Hall Effect Joystick, đi kèm Dock sạc.', '<h2>8BitDo Ultimate Bluetooth</h2><p>Đỉnh cao tay cầm chơi game với cần gạt Hall Effect chống trôi, đi kèm dock sạc vô cùng tiện lợi. Hỗ trợ phần mềm tùy chỉnh sâu.</p>', 'Tặng kèm Dock sạc', '{"Kết nối":"Bluetooth/2.4G/USB-C","Pin":"1000mAh (22 giờ)","Tương thích":"Switch, Windows","Tính năng":"Hall Effect Joystick, Dock sạc"}', 'Tay cầm 8BitDo Ultimate Bluetooth', 'Tay cầm 8BitDo Ultimate Bluetooth chính hãng kèm Dock sạc.', 25);

-- 26. GIÁ TREO TAI NGHE
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('Giá treo tai nghe Razer Base Station V2 Chroma', 'razer-base-station-v2-chroma', 'GT-RZ-BSV2', @razer, 1890000, 1690000, 'https://m.media-amazon.com/images/I/61XzT0x7H1L._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '460g', 20, 1, 1, NOW(), 'Giá treo tai nghe Razer tích hợp hub USB và LED RGB Chroma.', '<h2>Razer Base Station V2 Chroma</h2><p>Giá treo tai nghe kiêm USB Hub cao cấp từ Razer, trang bị 2 cổng USB 3.1 và DAC âm thanh vòm 7.1, LED Chroma 16.8 triệu màu.</p>', 'Freeship toàn quốc', '{"Cổng kết nối":"2x USB 3.1, 1x 3.5mm combo","LED":"Razer Chroma RGB","DAC":"Âm thanh vòm 7.1","Chất liệu":"Nhôm"}', 'Giá treo tai nghe Razer Base Station V2', 'Giá treo tai nghe RGB cao cấp Razer Base Station V2 Chroma.', 26),
('Giá treo tai nghe Corsair ST100 RGB', 'corsair-st100-rgb', 'GT-CS-ST100', @corsair, 1790000, 1590000, 'https://m.media-amazon.com/images/I/61xJjO-HkLL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '700g', 15, 0, 1, NOW(), 'Giá treo Corsair ST100 cao cấp với nhôm nguyên khối, LED RGB và DAC 7.1.', '<h2>Corsair ST100 RGB</h2><p>Được làm từ nhôm cao cấp, ST100 tích hợp LED RGB 9 vùng, 2 cổng USB 3.1 và DAC 7.1 mang lại trải nghiệm âm thanh sống động.</p>', 'Freeship', '{"Cổng kết nối":"2x USB 3.1, 1x 3.5mm","LED":"RGB 9 vùng","DAC":"Virtual 7.1 surround","Chất liệu":"Nhôm nguyên khối"}', 'Giá treo tai nghe Corsair ST100 RGB', 'Giá treo tai nghe nhôm Corsair ST100 RGB.', 26);

-- 27. CHUỘT GAMING
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('Chuột Logitech G Pro X Superlight', 'logitech-g-pro-x-superlight', 'CG-LG-GPXS', @logitech, 3490000, 2990000, 'https://m.media-amazon.com/images/I/51uy8gOG-iL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, '70 giờ', '63g', 45, 1, 1, NOW(), 'Chuột gaming không dây siêu nhẹ Logitech G Pro X Superlight, cảm biến HERO 25K.', '<h2>Logitech G Pro X Superlight</h2><p>Chuột gaming không dây siêu nhẹ (dưới 63g), công nghệ LIGHTSPEED và cảm biến HERO 25K chính xác nhất của Logitech.</p>', 'Tặng feet chuột PTFE', '{"Cảm biến":"HERO 25K","DPI":"25,600","Trọng lượng":"<63g","Kết nối":"LIGHTSPEED Wireless","Pin":"70 giờ"}', 'Logitech G Pro X Superlight', 'Chuột Logitech G Pro X Superlight siêu nhẹ.', 27),
('Chuột Razer DeathAdder V3 Pro', 'razer-deathadder-v3-pro', 'CG-RZ-DAV3P', @razer, 3690000, 3190000, 'https://m.media-amazon.com/images/I/51rRtbFpDbL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, '90 giờ', '63g', 30, 1, 1, NOW(), 'Chuột Razer DeathAdder V3 Pro siêu nhẹ, công thái học, cảm biến Focus Pro 30K.', '<h2>Razer DeathAdder V3 Pro</h2><p>Thiết kế công thái học huyền thoại nay nhẹ hơn bao giờ hết (63g), cảm biến Focus Pro 30K Optical và switch quang học thế hệ 3.</p>', 'Tặng Grip Tape', '{"Cảm biến":"Focus Pro 30K Optical","DPI":"30,000","Trọng lượng":"63g","Kết nối":"Razer HyperSpeed Wireless","Pin":"90 giờ"}', 'Razer DeathAdder V3 Pro', 'Chuột gaming Razer DeathAdder V3 Pro chính hãng.', 27);

-- 28. USB
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('USB SanDisk Ultra Dual Drive Luxe Type-C 128GB', 'sandisk-ultra-dual-drive-luxe-128gb', 'USB-SD-128G', @sandisk, 450000, 350000, 'https://m.media-amazon.com/images/I/61U7T1koQqL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '20g', 100, 0, 1, NOW(), 'USB SanDisk 128GB kim loại, 2 đầu Type-C và Type-A tốc độ 150MB/s.', '<h2>SanDisk Ultra Dual Drive Luxe</h2><p>Chép dữ liệu dễ dàng giữa điện thoại USB-C và máy tính với USB vỏ kim loại cao cấp, tốc độ đọc 150MB/s.</p>', 'Bảo hành 5 năm', '{"Dung lượng":"128GB","Giao tiếp":"USB Type-C & Type-A","Tốc độ đọc":"150MB/s","Chất liệu":"Kim loại"}', 'USB SanDisk Type-C 128GB', 'USB SanDisk Ultra Dual Drive Luxe Type-C 128GB.', 28),
('USB Kingston DataTraveler Max 256GB', 'kingston-datatraveler-max-256gb', 'USB-KS-MAX256', @kingston, 990000, 850000, 'https://m.media-amazon.com/images/I/51r-E1qQ0QL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '12g', 60, 1, 1, NOW(), 'USB Type-C cực nhanh với tốc độ lên đến 1000MB/s chuẩn USB 3.2 Gen 2.', '<h2>Kingston DataTraveler Max</h2><p>Tốc độ phá vỡ kỷ lục đối với một chiếc USB flash drive. Lên đến 1000MB/s đọc và 900MB/s ghi chuẩn USB 3.2 Gen 2.</p>', 'Tặng dây đeo', '{"Dung lượng":"256GB","Giao tiếp":"USB Type-C 3.2 Gen 2","Tốc độ đọc":"1000MB/s","Tốc độ ghi":"900MB/s"}', 'USB Kingston DataTraveler Max 256GB', 'USB Kingston DT Max 256GB Type-C siêu tốc.', 28);

-- 29. Ổ CỨNG DI ĐỘNG
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('Ổ cứng di động WD My Passport 1TB', 'wd-my-passport-1tb', 'HDD-WD-MP1T', @wd, 1590000, 1390000, 'https://m.media-amazon.com/images/I/61iP+TtyD1L._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '120g', 50, 0, 1, NOW(), 'Ổ cứng HDD di động Western Digital My Passport 1TB USB 3.2, bảo mật mật khẩu.', '<h2>WD My Passport 1TB</h2><p>Lưu trữ an toàn với WD My Passport, tích hợp phần mềm backup tự động và bảo mật mã hóa AES 256-bit phần cứng.</p>', 'Tặng túi chống sốc', '{"Dung lượng":"1TB","Loại":"HDD","Giao tiếp":"USB 3.2 Gen 1","Bảo mật":"AES 256-bit hardware encryption"}', 'Ổ cứng WD My Passport 1TB', 'Ổ cứng di động WD My Passport 1TB chính hãng.', 29),
('Ổ cứng SSD di động Samsung T7 Shield 1TB', 'samsung-t7-shield-1tb', 'SSD-SS-T7S1T', @samsung, 2990000, 2490000, 'https://m.media-amazon.com/images/I/51y4i1D4gXL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '98g', 40, 1, 1, NOW(), 'SSD di động Samsung T7 Shield siêu bền, chống nước IP65, tốc độ 1050MB/s.', '<h2>Samsung T7 Shield 1TB</h2><p>Bền bỉ, chống nước và bụi IP65, chống rơi 3 mét. Tốc độ đọc lên tới 1050MB/s và ghi 1000MB/s.</p>', 'Tặng cáp USB-C', '{"Dung lượng":"1TB","Loại":"SSD","Giao tiếp":"USB 3.2 Gen 2 (Type-C)","Tốc độ":"Đọc 1050MB/s, Ghi 1000MB/s","Bảo vệ":"IP65, Chống sốc"}', 'SSD Samsung T7 Shield 1TB', 'Ổ cứng SSD di động Samsung T7 Shield 1TB.', 29);

-- 30. BỘ PHÁT WIFI
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('Router Wifi TP-Link Archer AX73 AX5400', 'tp-link-archer-ax73-ax5400', 'WIFI-TP-AX73', @tplink, 2690000, 2190000, 'https://m.media-amazon.com/images/I/61H4PInKHzL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '600g', 30, 1, 1, NOW(), 'Bộ phát Wifi 6 TP-Link Archer AX73 chuẩn AX5400, 6 ăng-ten, phủ sóng cực rộng.', '<h2>TP-Link Archer AX73</h2><p>Trải nghiệm mạng Wi-Fi 6 siêu tốc với tốc độ lên đến 5400Mbps, 6 ăng-ten hiệu suất cao phủ sóng mọi ngóc ngách nhà bạn.</p>', 'Tặng cáp LAN Cat7', '{"Chuẩn Wifi":"Wi-Fi 6 (802.11ax)","Băng tần":"Kép (2.4GHz & 5GHz)","Tốc độ":"5400 Mbps","Ăng-ten":"6 ăng-ten ngoài","Cổng":"1x WAN Gigabit, 4x LAN Gigabit, 1x USB 3.0"}', 'Router TP-Link Archer AX73', 'Bộ phát Wi-Fi 6 TP-Link Archer AX73.', 30),
('Router Wifi Asus RT-AX82U AX5400', 'asus-rt-ax82u-ax5400', 'WIFI-AS-AX82U', @asus, 4990000, 4290000, 'https://m.media-amazon.com/images/I/71uA-a-v4fL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '740g', 20, 1, 1, NOW(), 'Bộ phát Wifi Gaming Asus RT-AX82U chuẩn Wifi 6, LED Aura RGB.', '<h2>Asus RT-AX82U</h2><p>Router gaming mạnh mẽ với đèn LED Aura RGB tùy chỉnh. Tối ưu hóa băng thông cho game với Mobile Game Mode và tốc độ 5400Mbps.</p>', 'Bảo hành 3 năm', '{"Chuẩn Wifi":"Wi-Fi 6 (802.11ax)","Tốc độ":"5400 Mbps","Tính năng":"Aura RGB, AiMesh, Mobile Game Mode","Cổng":"1x WAN Gigabit, 4x LAN Gigabit, 1x USB 3.2"}', 'Router Asus RT-AX82U Gaming', 'Bộ phát Wi-Fi 6 Gaming Asus RT-AX82U.', 30);

-- 31. USB WIFI
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('USB Wifi TP-Link Archer T3U AC1300', 'tp-link-archer-t3u-ac1300', 'UWF-TP-T3U', @tplink, 350000, 250000, 'https://m.media-amazon.com/images/I/61r5T7GZ42L._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '10g', 100, 0, 1, NOW(), 'USB Wifi thu sóng băng tần kép AC1300 cực nhỏ gọn.', '<h2>TP-Link Archer T3U</h2><p>Kích thước mini gọn nhẹ, công nghệ MU-MIMO cho trải nghiệm mạng không dây tốc độ cao AC1300 trên PC/Laptop.</p>', 'Giảm 50K', '{"Chuẩn Wifi":"AC1300","Băng tần":"Kép (2.4GHz/5GHz)","Giao tiếp":"USB 3.0","Kích thước":"Siêu nhỏ"}', 'USB Wifi TP-Link Archer T3U', 'USB Wifi thu sóng TP-Link Archer T3U AC1300.', 31);

-- 32. CÁP MẠNG
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('Cáp mạng Ugreen Cat8 RJ45 Dẹt 2m', 'cap-mang-ugreen-cat8-det-2m', 'CM-UG-CAT8-2M', @ugreen, 199000, 149000, 'https://m.media-amazon.com/images/I/71u9iU3zI-L._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '80g', 150, 0, 1, NOW(), 'Cáp mạng LAN Ugreen chuẩn Cat8, thiết kế dây dẹt, tốc độ 40Gbps.', '<h2>Ugreen Cat8 Ethernet Cable</h2><p>Cáp mạng Cat8 tốc độ siêu tốc 40Gbps/2000MHz. Thiết kế dẹt dễ dàng đi dây dưới thảm hoặc góc tường.</p>', 'Mua 2 tặng 1', '{"Chuẩn":"Cat 8","Tốc độ":"40Gbps / 2000MHz","Chiều dài":"2 mét","Thiết kế":"Dây dẹt","Chất liệu":"Lõi đồng nguyên chất"}', 'Cáp mạng Ugreen Cat8 2m', 'Cáp mạng Ugreen Cat8 tốc độ 40Gbps.', 32),
('Cáp mạng Baseus Cat7 Bện Nilon 3m', 'cap-mang-baseus-cat7-3m', 'CM-BS-CAT7-3M', @baseus, 150000, 99000, 'https://m.media-amazon.com/images/I/61YhO148D1L._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '100g', 200, 0, 1, NOW(), 'Cáp mạng LAN Baseus chuẩn Cat7, dây bện nilon chống đứt, tốc độ 10Gbps.', '<h2>Baseus Cat7 Ethernet Cable</h2><p>Cáp mạng siêu bền bọc vải dù nilon, đầu cáp mạ vàng chống nhiễu, chuẩn Cat7 10Gbps ổn định cho gaming và streaming.</p>', 'Freeship', '{"Chuẩn":"Cat 7","Tốc độ":"10Gbps / 600MHz","Chiều dài":"3 mét","Vật liệu":"Bện Nilon chống đứt"}', 'Cáp mạng Baseus Cat7 3m', 'Cáp mạng LAN Baseus Cat7 3m siêu bền.', 32);

-- 33. CAMERA WIFI
INSERT INTO product (name, slug, sku, brand_id, price, sale_price, image, cpu, ram, ssd, screen, vga, battery, weight, stock, featured, active, created_at, description, content, promotion, specs, meta_title, meta_description, category_id) VALUES
('Camera Wifi Xiaomi Smart Camera C300', 'xiaomi-smart-camera-c300', 'CAM-XM-C300', @xiaomi, 890000, 690000, 'https://m.media-amazon.com/images/I/51wXF1R6kEL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '327g', 60, 1, 1, NOW(), 'Camera IP Wifi Xiaomi C300 độ phân giải 2K, xoay 360 độ, theo dõi chuyển động AI.', '<h2>Xiaomi Smart Camera C300</h2><p>Độ phân giải 2K siêu nét, khẩu độ F1.4 thu sáng tốt trong đêm. Xoay 360 độ quan sát toàn cảnh, đàm thoại 2 chiều rõ ràng.</p>', 'Tặng thẻ nhớ 32GB', '{"Độ phân giải":"2K (2304x1296)","Góc nhìn":"360° ngang, 108° dọc","Lưu trữ":"Thẻ nhớ MicroSD (tối đa 256GB)","Kết nối":"Wi-Fi 2.4GHz","Tính năng":"Đàm thoại 2 chiều, Night Vision, AI Human Detection"}', 'Camera Wifi Xiaomi C300 2K', 'Camera an ninh Xiaomi C300 2K.', 33),
('Camera Wifi TP-Link Tapo C200', 'tp-link-tapo-c200', 'CAM-TP-C200', @tplink, 650000, 490000, 'https://m.media-amazon.com/images/I/61kM50P4vWL._SL1500_.jpg', NULL, NULL, NULL, NULL, NULL, NULL, '260g', 80, 0, 1, NOW(), 'Camera IP Wifi TP-Link Tapo C200 1080p, xoay 360 độ, phát hiện chuyển động.', '<h2>TP-Link Tapo C200</h2><p>Camera an ninh gia đình giá rẻ, xoay 360 độ, quay phim Full HD 1080p. Hỗ trợ cảnh báo âm thanh và ánh sáng khi phát hiện kẻ gian.</p>', 'Tặng thẻ nhớ 32GB', '{"Độ phân giải":"1080p Full HD","Góc nhìn":"360° ngang, 114° dọc","Lưu trữ":"Thẻ nhớ MicroSD (tối đa 128GB)","Kết nối":"Wi-Fi 2.4GHz","Tính năng":"Night Vision, Đàm thoại 2 chiều"}', 'Camera Wifi TP-Link Tapo C200', 'Camera an ninh TP-Link Tapo C200 1080p.', 33);
